# Generated by Django 6.0.4 on 2026-06-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogecko',
            name='avatar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuariogecko',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usuariogecko',
            name='direccion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usuariogecko',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariogecko',
            name='puesto',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
