services:
  backend:
    build: ./backend/gecko_tcg
    container_name: django_backend
    volumes:
      - ./backend/gecko_tcg:/app
      - ./backend/gecko_tcg/wallet:/app/wallet:ro
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    env_file:
      - ./backend/gecko_tcg/.env
    networks:
      - gecko_network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - gecko_network

networks:
  gecko_network:
    driver: bridge