import type { Producto } from '../types';

// Mock de productos basado en el esquema real de la BD (Oracle - QUIS)
export const mockProductos: Producto[] = [
  // --- CARTAS ---
  {
    id_producto: 1,
    codigo_barras: '4007110899991',
    nombre: 'Charizard EX',
    descripcion: 'Carta holo rara de Charizard del set Obsidian Flames',
    stock: 3,
    precio_base: 25000,
    categoria: 'Carta',
    rareza: 'Ultra Rara',
    edicion: 'Obsidian Flames',
    estado: 'Mint',
    precio_mercado: 32000,
  },
  {
    id_producto: 2,
    codigo_barras: '4007110899992',
    nombre: 'Pikachu V',
    descripcion: 'Carta Pikachu V del set Crown Zenith',
    stock: 10,
    precio_base: 5000,
    categoria: 'Carta',
    rareza: 'Rara',
    edicion: 'Crown Zenith',
    estado: 'Near Mint',
    precio_mercado: 7500,
  },
  {
    id_producto: 3,
    codigo_barras: '4007110899993',
    nombre: 'Mewtwo VSTAR',
    descripcion: 'Carta Mewtwo VSTAR del set Pokemon GO',
    stock: 0,
    precio_base: 18000,
    categoria: 'Carta',
    rareza: 'Ultra Rara',
    edicion: 'Pokemon GO',
    estado: 'Mint',
    precio_mercado: 22000,
  },
  // --- SOBRES ---
  {
    id_producto: 4,
    codigo_barras: '4007110899994',
    nombre: 'Sobre Paldea Evolved',
    descripcion: 'Sobre de 10 cartas del set Paldea Evolved',
    stock: 50,
    precio_base: 3500,
    categoria: 'Sobre',
    cant_cartas: 10,
    serie: 'Scarlet & Violet',
  },
  {
    id_producto: 5,
    codigo_barras: '4007110899995',
    nombre: 'Sobre Obsidian Flames',
    descripcion: 'Sobre de 10 cartas del set Obsidian Flames',
    stock: 35,
    precio_base: 3500,
    categoria: 'Sobre',
    cant_cartas: 10,
    serie: 'Scarlet & Violet',
  },
  {
    id_producto: 6,
    codigo_barras: '4007110899996',
    nombre: 'Sobre Crown Zenith',
    descripcion: 'Sobre de 10 cartas del set Crown Zenith',
    stock: 8,
    precio_base: 4000,
    categoria: 'Sobre',
    cant_cartas: 10,
    serie: 'Sword & Shield',
  },
  // --- CAJAS ---
  {
    id_producto: 7,
    codigo_barras: '4007110899997',
    nombre: 'Caja Elite Trainer Paldea Evolved',
    descripcion: 'ETB oficial con 9 sobres y accesorios',
    stock: 5,
    precio_base: 45000,
    categoria: 'Caja',
    cant_sobres: 9,
  },
  {
    id_producto: 8,
    codigo_barras: '4007110899998',
    nombre: 'Caja Booster Bundle Obsidian Flames',
    descripcion: 'Bundle con 6 sobres de Obsidian Flames',
    stock: 12,
    precio_base: 22000,
    categoria: 'Caja',
    cant_sobres: 6,
  },
];

export default mockProductos;