# Generated by Django 6.0.4 on 2026-05-13 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('Carta', 'Carta Individual'), ('Sobre', 'Sobre de Cartas'), ('Caja', 'Caja de Sobres')], max_length=30)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'PRODUCTO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoCarta',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='carta', serialize=False, to='productos.producto')),
                ('rareza', models.CharField(choices=[('Común', 'Común'), ('Poco Común', 'Poco Común'), ('Rara', 'Rara'), ('Muy Rara', 'Muy Rara'), ('Holográfica', 'Holográfica')], max_length=50)),
                ('edicion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Nueva', 'Nueva'), ('Excelente', 'Excelente'), ('Buena', 'Buena'), ('Usada', 'Usada'), ('Dañada', 'Dañada')], max_length=20)),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Producto Carta',
                'verbose_name_plural': 'Productos Cartas',
                'db_table': 'PRODUCTO_CARTA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoSobre',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sobre', serialize=False, to='productos.producto')),
                ('cant_cartas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('serie', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Producto Sobre',
                'verbose_name_plural': 'Productos Sobres',
                'db_table': 'PRODUCTO_SOBRE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoCaja',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caja', serialize=False, to='productos.producto')),
                ('cant_sobres', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Producto Caja',
                'verbose_name_plural': 'Productos Cajas',
                'db_table': 'PRODUCTO_CAJA',
                'managed': True,
            },
        ),
    ]
