# Generated by Django 6.0.4 on 2026-05-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(choices=[('Ventas', 'Reporte de Ventas'), ('Inventario', 'Reporte de Inventario'), ('Productos_Bajos', 'Reporte de Productos con Stock Bajo'), ('Vendedores', 'Reporte de Desempeño de Vendedores'), ('Ganancias', 'Reporte de Ganancias')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'REPORTE',
                'ordering': ['-fecha_reporte'],
                'managed': False,
            },
        ),
    ]
